package com.mirco_grid.backend.service;

import java.util.List;

/** "Your Maximum Outcome Plan" - the wizard's output. */
public record OutcomePlan(
        String suburb,
        WizardAnswers.Role role,
        /** Headline range, dollars per year, across everything recommended. */
        int totalAnnualLow,
        int totalAnnualHigh,
        /** How many of the recommendations cost nothing to start. */
        int zeroUpfrontCount,
        List<Recommendation> doThisWeek,
        List<Recommendation> doThisMonth,
        GridStatus grid,
        /** What the grid state means for this person, right now. */
        String gridTip,
        List<String> maximiseTips,
        /** Follow-ups generated by anything answered "not sure". */
        List<String> findOutNext) {

    /** One action, with what it is worth and what it costs to start. */
    public record Recommendation(
            String id,
            String title,
            String summary,
            int annualLow,
            int annualHigh,
            int upfrontCost,
            Effort effort,
            Timing timing,
            String howTo,
            String source) {

        public boolean isFree() {
            return upfrontCost == 0;
        }
    }

    public enum Effort { ONE_TAP, SHORT, INVOLVED }

    public enum Timing { THIS_WEEK, THIS_MONTH }
}
